/**
 * @generated by scripts/codegen-schemas.ts from shared/schemas/*.schema.json
 * DO NOT EDIT MANUALLY — run `npm run codegen:schemas` to regenerate.
 * Protocol version: 1.0
 */

// ---------------------------------------------------------------------------
// Shared primitives
// ---------------------------------------------------------------------------

export const PROTOCOL_VERSION = "1.0" as const;

export type ProtocolVersion = typeof PROTOCOL_VERSION;

export interface ErrorDetail {
  code: string;
  message: string;
  retryable: boolean;
}

// ---------------------------------------------------------------------------
// Requests (Electron main → Python daemon)
// ---------------------------------------------------------------------------

export interface AgentTaskRequest {
  version: ProtocolVersion;
  meta: "agent_task";
  /** User-supplied prompt */
  prompt: string;
  /**
   * Per-target CDP WebSocket URL: ws://host:port/devtools/page/{targetId}
   * Enforces active-tab-only at transport layer (plan principle #4).
   */
  per_target_cdp_url: string;
  /** Unique task identifier (UUID recommended) */
  task_id: string;
}

export interface CancelTaskRequest {
  version: ProtocolVersion;
  meta: "cancel_task";
  task_id: string;
}

export interface SetActiveTargetRequest {
  version: ProtocolVersion;
  meta: "set_active_target";
  per_target_cdp_url: string;
}

export interface PingRequest {
  version: ProtocolVersion;
  meta: "ping";
}

export interface ShutdownRequest {
  version: ProtocolVersion;
  meta: "shutdown";
}

export type DaemonRequest =
  | AgentTaskRequest
  | CancelTaskRequest
  | SetActiveTargetRequest
  | PingRequest
  | ShutdownRequest;

// ---------------------------------------------------------------------------
// Responses (Python daemon → Electron main, synchronous reply)
// ---------------------------------------------------------------------------

export interface SuccessResponse {
  version: ProtocolVersion;
  ok: true;
  result?: unknown;
}

export interface ErrorResponse {
  version: ProtocolVersion;
  ok: false;
  error: ErrorDetail;
}

export type DaemonResponse = SuccessResponse | ErrorResponse;

// ---------------------------------------------------------------------------
// Push Events (Python daemon → Electron main, unsolicited)
// ---------------------------------------------------------------------------

export interface TaskStartedEvent {
  version: ProtocolVersion;
  event: "task_started";
  task_id: string;
  /** ISO 8601 timestamp */
  started_at: string;
}

export interface StepStartEvent {
  version: ProtocolVersion;
  event: "step_start";
  task_id: string;
  /** 1-based step number */
  step: number;
  plan: string;
}

export interface StepResultEvent {
  version: ProtocolVersion;
  event: "step_result";
  task_id: string;
  step: number;
  result: unknown;
  duration_ms: number;
}

export interface StepErrorEvent {
  version: ProtocolVersion;
  event: "step_error";
  task_id: string;
  step: number;
  error: ErrorDetail;
}

export interface TaskDoneEvent {
  version: ProtocolVersion;
  event: "task_done";
  task_id: string;
  result: unknown;
  steps_used: number;
  tokens_used: number;
}

export type TaskFailureReason =
  | "step_budget_exhausted"
  | "token_budget_exhausted"
  | "sandbox_violation"
  | "llm_error"
  | "cdp_error"
  | "internal_error";

export interface TaskFailedEvent {
  version: ProtocolVersion;
  event: "task_failed";
  task_id: string;
  reason: TaskFailureReason;
  partial_result?: unknown;
}

export interface TaskCancelledEvent {
  version: ProtocolVersion;
  event: "task_cancelled";
  task_id: string;
}

export interface TargetLostEvent {
  version: ProtocolVersion;
  event: "target_lost";
  task_id: string;
  /** CDP target ID that was detached */
  target_id: string;
}

export type AgentEvent =
  | TaskStartedEvent
  | StepStartEvent
  | StepResultEvent
  | StepErrorEvent
  | TaskDoneEvent
  | TaskFailedEvent
  | TaskCancelledEvent
  | TargetLostEvent;

export type AgentEventType = AgentEvent["event"];

// ---------------------------------------------------------------------------
// Tab state (Electron main ↔ renderers via contextBridge)
// ---------------------------------------------------------------------------

export interface TabInfo {
  tab_id: string;
  url: string;
  title: string;
  favicon_url?: string;
  is_loading: boolean;
  can_go_back: boolean;
  can_go_forward: boolean;
  /** Set once tab has navigated */
  per_target_cdp_url?: string;
}

export interface TabActivatedEvent {
  version: ProtocolVersion;
  event: "tab-activated";
  tab_id: string;
  per_target_cdp_url: string;
}

export interface TabOpenedEvent {
  version: ProtocolVersion;
  event: "tab-opened";
  tab: TabInfo;
}

export interface TabClosedEvent {
  version: ProtocolVersion;
  event: "tab-closed";
  tab_id: string;
}

export interface TabUpdatedEvent {
  version: ProtocolVersion;
  event: "tab-updated";
  tab: TabInfo;
}

export interface TabReorderedEvent {
  version: ProtocolVersion;
  event: "tab-reordered";
  /** Full ordered array of tab IDs after reorder */
  tab_ids: string[];
}

export interface TabsRestoredEvent {
  version: ProtocolVersion;
  event: "tabs-restored";
  tabs: TabInfo[];
  active_tab_id: string;
}

export type TabEvent =
  | TabActivatedEvent
  | TabOpenedEvent
  | TabClosedEvent
  | TabUpdatedEvent
  | TabReorderedEvent
  | TabsRestoredEvent;


// ---------------------------------------------------------------------------
// Runtime validation helpers (inline, no external deps)
// ---------------------------------------------------------------------------

/**
 * Type guard: checks that a parsed JSON object has version "1.0" and the
 * expected event/meta discriminant. Throws if version is unknown so callers
 * can log a warning rather than crash.
 */
export function assertVersion(msg: unknown): asserts msg is { version: string } {
  if (
    typeof msg !== "object" ||
    msg === null ||
    typeof (msg as Record<string, unknown>)["version"] !== "string"
  ) {
    throw new Error("IPC message missing version field");
  }
  const v = (msg as Record<string, unknown>)["version"];
  if (v !== PROTOCOL_VERSION) {
    throw new Error(`IPC version mismatch: expected ${PROTOCOL_VERSION}, got ${String(v)}`);
  }
}

export function isDaemonResponse(msg: unknown): msg is DaemonResponse {
  if (typeof msg !== "object" || msg === null) return false;
  const m = msg as Record<string, unknown>;
  return typeof m["ok"] === "boolean" && m["version"] === PROTOCOL_VERSION;
}

export function isAgentEvent(msg: unknown): msg is AgentEvent {
  if (typeof msg !== "object" || msg === null) return false;
  const m = msg as Record<string, unknown>;
  return typeof m["event"] === "string" && m["version"] === PROTOCOL_VERSION;
}

export function isTabEvent(msg: unknown): msg is TabEvent {
  if (typeof msg !== "object" || msg === null) return false;
  const m = msg as Record<string, unknown>;
  const tabEvents: string[] = [
    "tab-activated", "tab-opened", "tab-closed",
    "tab-updated", "tab-reordered", "tabs-restored",
  ];
  return typeof m["event"] === "string" &&
    tabEvents.includes(m["event"] as string) &&
    m["version"] === PROTOCOL_VERSION;
}

/** Parse a newline-delimited JSON line from the daemon socket */
export function parseSocketLine(line: string): AgentEvent | DaemonResponse {
  let parsed: unknown;
  try {
    parsed = JSON.parse(line);
  } catch (err) {
    throw new Error(`Failed to parse socket line as JSON: ${line.slice(0, 200)}`, { cause: err });
  }
  assertVersion(parsed);
  return parsed as AgentEvent | DaemonResponse;
}

/** Build a request with version stamped in */
export function makeRequest<T extends Omit<DaemonRequest, "version">>(
  req: T
): T & { version: ProtocolVersion } {
  return { ...req, version: PROTOCOL_VERSION };
}
